# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  vsky
subtitle: 好好学习，天天向上
name: vsky 
email: vsky.tester@foxmail.com
description: 本站是vsky的技术分享博客。内容涵盖生活故事、测试技术类经验、自动化测试、性能测试等等知识分享及个人工作笔记。
keywords: vsky,软件测试,性能测试,压力测试,自动化测试,jmeter,selenium,python,
encoding: "utf-8"
favicon: favicon.ico 

repository: baqixiaozhu/vsky
github_url: https://github.com/baqixiaozhu/vsky
url: https://baqixiaozhu.github.io/vsky
enforce_ssl: vsky

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /python.html
    label: Python  
    target: _self

  -
    href: /jmeter.html
    label: jmeter
    target: _self

  -
    href: /selenium.html
    label: selenium
    target: _self   

  -
    href: /life.html
    label: 故事
    target: _self

  -
    href: /autoit.html
    label: autoit
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /测试工具.html
    label: 测试工具
    target: _self
    subnav:

      -
        subHref: /selenium.html
        subLabel: selenium

      -
        subHref: /jmeter.html
        subLabel: jmeter

  -
    href: /spring-cloud.html
    label: 性能测试
    target: _self

  -
    
    href: http://www.justdojava.com
    label: 移动端测试
    target: _blank
    subnav:

      -
        subHref: /java.html
        subLabel: appium
        
      -
        subHref: http://www.justdojava.com
        subLabel: robotium
        target: _blank

  -
    href: /archives.html
    label: Archives
    target: _self

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /payment.html
    label: other     
    target: _self

  -
    href: /fastdfs.html
    label: shell
    target: _blank

  -
    href: /mongodb.html
    label: mysql
    target: _blank

  -
    href: /docker.html
    label: api
    target: _blank

  -
    href: /open-source.html
    label: Code  
    target: _blank

  -
    href: /gitchat.html
    label: Chat
    target: _blank

  -
    href: /geektime.html
    label: none
    target: _blank


# selected articles
classes:

  -
    href: /life.html
    name: 日常故事
    describe: 生活就是故事，故事就是生活

  -
    href: /arch.html
    name: 自动化测试
    describe: 一切自动化均为效率而考虑

  -
    href: /java.html
    name: 测试开发
    describe: 更进一层


# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: vsky
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: vsky
    repo: blog-comments
    oauth:
        client_id: 61bfc53d957e74e78f8f
        client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: vsky
    repo: blog-comments
    clientID: 61bfc53d957e74e78f8f
    clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
